apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ns_with_annotations_and_labels.yml
  - quotas.yml
  - limit_ranges.yml

# For limit ranges and quotas
namespace: demo
commonLabels:
  env: demoenv
  ver: "1.0"
