apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: hello-web
    env: dev
    owner: hello-web-team
    ver: v1.1
  annotations:
    kubernetes.io/change-cause: v1.1 with bug fix # rollout change clause
  name: hello-web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-web
      env: dev
      owner: hello-web-team      
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hello-web
        env: dev
        owner: hello-web-team
        ver: v1.1
    spec:
      containers:
        - image: ghcr.io/suren-m/hello-web:1.1
          name: hello-web
          resources: {}
status: {}
