apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: http-client
  name: http-client
spec:
  containers:
  - image: curlimages/curl:latest
    name: http-client
    command: ["sh", "-c", "sleep infinity"]
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
